### ISSUE TITLE
update mitla page

### ISSUE THREAD

**Issue by amundo** [mixtecnerds/health_in_mixtec#12]
![image](https://cloud.githubusercontent.com/assets/30924/22175185/0a877036-dfbe-11e6-9f8a-1baa45985cc0.png)

**Comment by amundo** [comment]
reopen if you want more changes em

**Comment by ejohnmartin** [comment]
You never uploaded the calendar activities.  The teachers are going to need that.
https://app.box.com/s/50dflgolxq1qt48uwvn4hw7w3ucqhhl3
https://app.box.com/s/uawei54hu29rvus2yhi30kclazrdjc83
https://app.box.com/s/5d9t7ocz9lmfkhw4t0dz7c6sohhknata

**Comment by amundo** [comment]
I think they are all there? 

http://westcoastmixtecs.com/mitla/book_activities.html

The links on this page work?

**Comment by ejohnmartin** [comment]
Hooray!!!  Good job!!!!
