### ISSUE TITLE
Contact Félix on tone project

### ISSUE THREAD

**Issue by amundo** [mixtecnerds/health_in_mixtec#13]
Félix Cortés at MICOP has contacted me on a tone analysis project for his variant (San Sebastián del Monte). 

I think we should reach out to him and ask if he is interested in hosting his stuff on wcm. It could be a good first point of contact with MICOP. We'd have to make sure that we let them know that MICOP could do whatever they want with the content too, including hosting it on mixteco.org (though I doubt they can manage that, I know their website situation and it is… broken).

**Comment by ejohnmartin** [comment]
I agree with you.

Sincerely,

Emily John M.
360.610.6871

**Comment by amundo** [comment]
i invited him to the wcm group, a good start
