### ISSUE TITLE
What should we call your role in something like http://westcoastmixtecs.com/health/depression_screening/?

### ISSUE THREAD

**Issue by amundo** [mixtecnerds/health_in_mixtec#21]
So, this is the underlying data (which I put together from your word processing file plus some munging in Audactiy):

http://westcoastmixtecs.com/health/depression_screening/depression_screening-dlx-text.json

Note that there are two parts to this data, `metadata` and `phrases`. The `metadata` looks like this right now:

```json
"metadata": {

    "title": "Depression screening",
    "speaker": "Demetrio Zurita Quiroz",
    "media": "depression_screening.mp3"

},
```

The best way to deliver this to people is, of course, HTML. But we should think about what kind of metadata we want behind the scene. You played a role in getting this thing to happen, and there’s also the source of the original Spanish (medicalspanish.com, I think it was?). 

It's very easy to forget about data like that (see? I've already forgotten the url…) so keeping it right inside the file together with the linguistic data is a good idea. 

We can use whatever role names you want: we could call you `editor` or `contributor` or whatever. 

I do think that if you ended up adding word-by-word glosses to this thing, it would make sense to add you as `linguist`. If you and I did that together, we could call ourselves `linguists`.

Wdyt?

**Comment by ejohnmartin** [comment]
medicalspanish.com was the source/inspiration for the original English, not Spanish.  I think we should both be called linguists.  Demetrio could be called translator.

**Comment by amundo** [comment]
this look good?

```json  "metadata": {
    "title": "Depression screening",
    "speaker": "Demetrio Zurita Quiroz",
    "translator": "Demetrio Zurita Quiroz",
    "translatedFrom": "http://medicalspanish.com/medical-spanish-dialogs/depression.html",
    "linguists": [
      "Emily John Martin",
      "Patrick Hall"
    ],
    "media": "depression_screening.mp3"
  },

```
